name: Automatic Branch Promotion
on:
  push:
    branches:
      - dev
      - staging

jobs:
  create-promotion-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          fetch-tags: false
          persist-credentials: true

      - name: Determine target branch
        id: set-target
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "target_branch=staging" >> $GITHUB_OUTPUT
            echo "source_branch=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "target_branch=main" >> $GITHUB_OUTPUT
            echo "source_branch=staging" >> $GITHUB_OUTPUT
          fi
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Check for changes
        id: check_changes
        run: |
          # Fetch the target branch
          git fetch origin ${{ steps.set-target.outputs.target_branch }}:${{ steps.set-target.outputs.target_branch }}

          # Check if target branch exists
          if ! git show-ref --verify --quiet refs/heads/${{ steps.set-target.outputs.target_branch }}; then
            echo "Target branch ${{ steps.set-target.outputs.target_branch }} does not exist"
            echo "changes_count=0" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Count changes between branches
          CHANGES=$(git rev-list --count ${{ steps.set-target.outputs.target_branch }}..${{ steps.set-target.outputs.source_branch }})
          echo "changes_count=$CHANGES" >> $GITHUB_OUTPUT
          echo "Found $CHANGES commits to promote"

      - name: Create promotion branch
        if: steps.check_changes.outputs.changes_count > 0
        run: |
          # Create a new branch from source
          git checkout -b auto-promote/${{ steps.set-target.outputs.source_branch }}-to-${{ steps.set-target.outputs.target_branch }} ${{ steps.set-target.outputs.source_branch }}
          git push -f origin auto-promote/${{ steps.set-target.outputs.source_branch }}-to-${{ steps.set-target.outputs.target_branch }}

      - name: Check for existing PR
        if: steps.check_changes.outputs.changes_count > 0
        id: check_pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `auto-promote/${process.env.SOURCE_BRANCH}-to-${process.env.TARGET_BRANCH}`,
              base: process.env.TARGET_BRANCH
            });
            if (prs.length > 0) {
              // Close existing PR
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prs[0].number,
                state: 'closed'
              });
            }
            return 0;
        env:
          SOURCE_BRANCH: ${{ steps.set-target.outputs.source_branch }}
          TARGET_BRANCH: ${{ steps.set-target.outputs.target_branch }}

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_count > 0
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-promote/${{ steps.set-target.outputs.source_branch }}-to-${{ steps.set-target.outputs.target_branch }}
          title: "[${{ steps.set-target.outputs.date }}] Promote ${{ steps.set-target.outputs.source_branch }} to ${{ steps.set-target.outputs.target_branch }}"
          body: |
            🔄 Automatic promotion PR

            This PR was automatically created to promote changes from `${{ steps.set-target.outputs.source_branch }}` to `${{ steps.set-target.outputs.target_branch }}`.

            ### Changes included:
            ${{ github.server_url }}/${{ github.repository }}/compare/${{ steps.set-target.outputs.target_branch }}...${{ steps.set-target.outputs.source_branch }}

            Please review the changes and merge when ready.
          labels: |
            automated-pr
            promotion
          base: ${{ steps.set-target.outputs.target_branch }}
          delete-branch: false
          rebase: false
          debug: true
