name: Automatic Branch Promotion
on:
  push:
    branches:
      - dev
      - staging

jobs:
  create-promotion-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Determine target branch
        id: set-target
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "target_branch=staging" >> $GITHUB_OUTPUT
            echo "source_branch=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "target_branch=main" >> $GITHUB_OUTPUT
            echo "source_branch=staging" >> $GITHUB_OUTPUT
          fi
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Check for changes
        id: check_changes
        run: |
          git fetch origin ${{ steps.set-target.outputs.target_branch }}:${{ steps.set-target.outputs.target_branch }}
          CHANGES=$(git log --oneline ${{ steps.set-target.outputs.target_branch }}..${{ steps.set-target.outputs.source_branch }} | wc -l)
          echo "changes_count=$CHANGES" >> $GITHUB_OUTPUT
          echo "Found $CHANGES commits to promote"
          git fetch origin ${{ steps.set-target.outputs.target_branch }}
          BEHIND_BY=$(git rev-list --count origin/${{ steps.set-target.outputs.target_branch }}..${{ steps.set-target.outputs.source_branch }})
          echo "changes_count=$BEHIND_BY" >> $GITHUB_OUTPUT
          echo "Found $BEHIND_BY commits to promote"

      - name: Create promotion branch
        if: steps.check_changes.outputs.changes_count > 0
        run: |
          # Create a new branch from the source branch
          git checkout -b auto-promote/${{ steps.set-target.outputs.source_branch }}-to-${{ steps.set-target.outputs.target_branch }} ${{ steps.set-target.outputs.source_branch }}
          # Push the branch to origin
          git push -u origin auto-promote/${{ steps.set-target.outputs.source_branch }}-to-${{ steps.set-target.outputs.target_branch }}

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_count > 0
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-promote/${{ steps.set-target.outputs.source_branch }}-to-${{ steps.set-target.outputs.target_branch }}
          title: "[${{ steps.set-target.outputs.date }}] Promote ${{ steps.set-target.outputs.source_branch }} to ${{ steps.set-target.outputs.target_branch }}"
          body: |
            🔄 Automatic promotion PR

            This PR was automatically created to promote changes from `${{ steps.set-target.outputs.source_branch }}` to `${{ steps.set-target.outputs.target_branch }}`.

            ### Changes included:
            ${{ github.server_url }}/${{ github.repository }}/compare/${{ steps.set-target.outputs.target_branch }}...${{ steps.set-target.outputs.source_branch }}

            Please review the changes and merge when ready.
          labels: |
            automated-pr
            promotion
          base: ${{ steps.set-target.outputs.target_branch }}
          delete-branch: true
