name: Sync Branches

on:
  push:
    branches:
      - dev
      - staging
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Sync branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync dev to staging
        if: github.ref == 'refs/heads/dev'
        uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "dev"
          TO_BRANCH: "staging"
          PULL_REQUEST_TITLE: "Sync: dev → staging"
          PULL_REQUEST_BODY: "Automated PR to sync changes from dev to staging"
          CONTENT_COMPARISON: true

      - name: Sync staging to main
        if: github.ref == 'refs/heads/staging'
        uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "staging"
          TO_BRANCH: "main"
          PULL_REQUEST_TITLE: "Sync: staging → main"
          PULL_REQUEST_BODY: "Automated PR to sync changes from staging to main"
          CONTENT_COMPARISON: true

      - name: Sync staging to dev (downsync)
        if: github.ref == 'refs/heads/staging'
        uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "staging"
          TO_BRANCH: "dev"
          PULL_REQUEST_TITLE: "Sync: staging → dev (downsync)"
          PULL_REQUEST_BODY: "Automated PR to sync changes from staging to dev"
          CONTENT_COMPARISON: true

      - name: Sync main to staging (downsync)
        if: github.ref == 'refs/heads/main'
        uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "main"
          TO_BRANCH: "staging"
          PULL_REQUEST_TITLE: "Sync: main → staging (downsync)"
          PULL_REQUEST_BODY: "Automated PR to sync changes from main to staging"
          CONTENT_COMPARISON: true
